[project]
name = "turbo-gst"
version = "0.1.1-alpha"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.1",
    "pyside6>=6.9.1",
    "qt-material>=2.17",
    "xlsxwriter>=3.2.5",
]

